services:
  dragonball-app-dev:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    container_name: dragonball-app-dev
    env_file:
      - .env.development
    ports:
      - 3000:3000
    volumes:
      - dragonball-db-dev:/app/db
    working_dir: /app
    command: yarn dev
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
  dragonball-app-test:
    build:
      context: ./
      dockerfile: Dockerfile
      target: test
    container_name: dragonball-app-test
    env_file:
      - .env.test
    working_dir: /app
    command: yarn test
  dragonball-app-prod:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    container_name: dragonball-app-prod
    env_file:
      - .env.production
    ports:
      - 4000:4000
    volumes:
      - dragonball-db-prod:/app/db
    working_dir: /app
    command: yarn start
volumes:
  dragonball-db-dev:
  dragonball-db-prod:
