name: Docker Image CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build -t longlong569/practice-one:latest
      - name: Push image to Docker hub
        run: docker push -t longlong569/practice-one:latest
